services:
  wellmed_lite_prod:
    container_name: wellmed_lite_prod
    image: wellmed-lite-prod
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile-lite
      target: production
    ports:
      - "${WELLMED_LITE_PORT:-8081}:${WELLMED_LITE_PORT:-8081}"
    volumes:
      - wellmed_lite_prod_storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - wellmed-core
    env_file:
      - .env.lite.prod
    command: >
      php artisan octane:frankenphp
      --host=0.0.0.0
      --port=${WELLMED_LITE_PORT:-8081}
      --workers=${PHP_CLI_SERVER_WORKERS:-4}
      --max-requests=1000

networks:
  wellmed-core:
    driver: bridge

volumes:  
  wellmed_lite_prod_storage:
